# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/unix_rid_capture/unix_rid_capture

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/unix_rid_capture/unix_rid_capture

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/unix_rid_capture/unix_rid_capture/CMakeFiles /home/runner/work/unix_rid_capture/unix_rid_capture//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/unix_rid_capture/unix_rid_capture/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rid_capture

# Build rule for target.
rid_capture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rid_capture
.PHONY : rid_capture

# fast build rule for target.
rid_capture/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/build
.PHONY : rid_capture/fast

#=============================================================================
# Target rules for targets named nrf_sniffer

# Build rule for target.
nrf_sniffer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nrf_sniffer
.PHONY : nrf_sniffer

# fast build rule for target.
nrf_sniffer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf_sniffer.dir/build.make CMakeFiles/nrf_sniffer.dir/build
.PHONY : nrf_sniffer/fast

#=============================================================================
# Target rules for targets named bluez_sniffer

# Build rule for target.
bluez_sniffer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bluez_sniffer
.PHONY : bluez_sniffer

# fast build rule for target.
bluez_sniffer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluez_sniffer.dir/build.make CMakeFiles/bluez_sniffer.dir/build
.PHONY : bluez_sniffer/fast

#=============================================================================
# Target rules for targets named m_per_deg

# Build rule for target.
m_per_deg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m_per_deg
.PHONY : m_per_deg

# fast build rule for target.
m_per_deg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m_per_deg.dir/build.make CMakeFiles/m_per_deg.dir/build
.PHONY : m_per_deg/fast

bluez_sniffer.o: bluez_sniffer.c.o
.PHONY : bluez_sniffer.o

# target to build an object file
bluez_sniffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/bluez_sniffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluez_sniffer.dir/build.make CMakeFiles/bluez_sniffer.dir/bluez_sniffer.c.o
.PHONY : bluez_sniffer.c.o

bluez_sniffer.i: bluez_sniffer.c.i
.PHONY : bluez_sniffer.i

# target to preprocess a source file
bluez_sniffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/bluez_sniffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluez_sniffer.dir/build.make CMakeFiles/bluez_sniffer.dir/bluez_sniffer.c.i
.PHONY : bluez_sniffer.c.i

bluez_sniffer.s: bluez_sniffer.c.s
.PHONY : bluez_sniffer.s

# target to generate assembly for a file
bluez_sniffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/bluez_sniffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluez_sniffer.dir/build.make CMakeFiles/bluez_sniffer.dir/bluez_sniffer.c.s
.PHONY : bluez_sniffer.c.s

display.o: display.c.o
.PHONY : display.o

# target to build an object file
display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/display.c.o
.PHONY : display.c.o

display.i: display.c.i
.PHONY : display.i

# target to preprocess a source file
display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/display.c.i
.PHONY : display.c.i

display.s: display.c.s
.PHONY : display.s

# target to generate assembly for a file
display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/display.c.s
.PHONY : display.c.s

export.o: export.c.o
.PHONY : export.o

# target to build an object file
export.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/export.c.o
.PHONY : export.c.o

export.i: export.c.i
.PHONY : export.i

# target to preprocess a source file
export.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/export.c.i
.PHONY : export.c.i

export.s: export.c.s
.PHONY : export.s

# target to generate assembly for a file
export.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/export.c.s
.PHONY : export.c.s

france.o: france.c.o
.PHONY : france.o

# target to build an object file
france.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/france.c.o
.PHONY : france.c.o

france.i: france.c.i
.PHONY : france.i

# target to preprocess a source file
france.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/france.c.i
.PHONY : france.c.i

france.s: france.c.s
.PHONY : france.s

# target to generate assembly for a file
france.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/france.c.s
.PHONY : france.c.s

m_per_deg.o: m_per_deg.c.o
.PHONY : m_per_deg.o

# target to build an object file
m_per_deg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/m_per_deg.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m_per_deg.dir/build.make CMakeFiles/m_per_deg.dir/m_per_deg.c.o
.PHONY : m_per_deg.c.o

m_per_deg.i: m_per_deg.c.i
.PHONY : m_per_deg.i

# target to preprocess a source file
m_per_deg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/m_per_deg.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m_per_deg.dir/build.make CMakeFiles/m_per_deg.dir/m_per_deg.c.i
.PHONY : m_per_deg.c.i

m_per_deg.s: m_per_deg.c.s
.PHONY : m_per_deg.s

# target to generate assembly for a file
m_per_deg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/m_per_deg.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m_per_deg.dir/build.make CMakeFiles/m_per_deg.dir/m_per_deg.c.s
.PHONY : m_per_deg.c.s

nrf_sniffer.o: nrf_sniffer.c.o
.PHONY : nrf_sniffer.o

# target to build an object file
nrf_sniffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf_sniffer.dir/build.make CMakeFiles/nrf_sniffer.dir/nrf_sniffer.c.o
.PHONY : nrf_sniffer.c.o

nrf_sniffer.i: nrf_sniffer.c.i
.PHONY : nrf_sniffer.i

# target to preprocess a source file
nrf_sniffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf_sniffer.dir/build.make CMakeFiles/nrf_sniffer.dir/nrf_sniffer.c.i
.PHONY : nrf_sniffer.c.i

nrf_sniffer.s: nrf_sniffer.c.s
.PHONY : nrf_sniffer.s

# target to generate assembly for a file
nrf_sniffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nrf_sniffer.dir/build.make CMakeFiles/nrf_sniffer.dir/nrf_sniffer.c.s
.PHONY : nrf_sniffer.c.s

opendroneid.o: opendroneid.c.o
.PHONY : opendroneid.o

# target to build an object file
opendroneid.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/opendroneid.c.o
.PHONY : opendroneid.c.o

opendroneid.i: opendroneid.c.i
.PHONY : opendroneid.i

# target to preprocess a source file
opendroneid.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/opendroneid.c.i
.PHONY : opendroneid.c.i

opendroneid.s: opendroneid.c.s
.PHONY : opendroneid.s

# target to generate assembly for a file
opendroneid.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/opendroneid.c.s
.PHONY : opendroneid.c.s

rid_capture.o: rid_capture.c.o
.PHONY : rid_capture.o

# target to build an object file
rid_capture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/rid_capture.c.o
.PHONY : rid_capture.c.o

rid_capture.i: rid_capture.c.i
.PHONY : rid_capture.i

# target to preprocess a source file
rid_capture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/rid_capture.c.i
.PHONY : rid_capture.c.i

rid_capture.s: rid_capture.c.s
.PHONY : rid_capture.s

# target to generate assembly for a file
rid_capture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/rid_capture.c.s
.PHONY : rid_capture.c.s

summary.o: summary.c.o
.PHONY : summary.o

# target to build an object file
summary.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/summary.c.o
.PHONY : summary.c.o

summary.i: summary.c.i
.PHONY : summary.i

# target to preprocess a source file
summary.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/summary.c.i
.PHONY : summary.c.i

summary.s: summary.c.s
.PHONY : summary.s

# target to generate assembly for a file
summary.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rid_capture.dir/build.make CMakeFiles/rid_capture.dir/summary.c.s
.PHONY : summary.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bluez_sniffer"
	@echo "... m_per_deg"
	@echo "... nrf_sniffer"
	@echo "... rid_capture"
	@echo "... bluez_sniffer.o"
	@echo "... bluez_sniffer.i"
	@echo "... bluez_sniffer.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... export.o"
	@echo "... export.i"
	@echo "... export.s"
	@echo "... france.o"
	@echo "... france.i"
	@echo "... france.s"
	@echo "... m_per_deg.o"
	@echo "... m_per_deg.i"
	@echo "... m_per_deg.s"
	@echo "... nrf_sniffer.o"
	@echo "... nrf_sniffer.i"
	@echo "... nrf_sniffer.s"
	@echo "... opendroneid.o"
	@echo "... opendroneid.i"
	@echo "... opendroneid.s"
	@echo "... rid_capture.o"
	@echo "... rid_capture.i"
	@echo "... rid_capture.s"
	@echo "... summary.o"
	@echo "... summary.i"
	@echo "... summary.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

